### ISSUE TITLE
error 503 webfleet connect; failure to read response

### ISSUE THREAD

**Issue by geopamplona** [flix-tech/webfleet-kafka-connector#8]
Hello
a few days ago there was an error in the webfleet connect platform and this caused the connector to fall several days
I attach the error
![imagen](https://user-images.githubusercontent.com/25028240/48712197-76ffb680-ec0d-11e8-8775-b71c9a9e73c8.png)

I think that applying try and catch could be solved, would this be correct?
Could you guide me on how to solve this error?

**Comment by AnkushKhanna** [comment]
I know what is wrong, let me create a PR, hopefully today. Thanks for pointing it out @geopamplona

**Comment by AnkushKhanna** [comment]
@geopamplona can you review https://github.com/flix-tech/webfleet-kafka-connector/pull/9 ?

**Comment by geopamplona** [comment]
that's great!
thank you
I review it throughout the day

**Comment by AnkushKhanna** [comment]
@geopamplona : any feedback? I would like to merge it today.

**Comment by geopamplona** [comment]
it seems ok
sorry for the delay

**Comment by AnkushKhanna** [comment]
https://github.com/flix-tech/webfleet-kafka-connector/pull/9
